### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by hariom282538** [tailot/nodebb-plugin-text2speech#1]
installed > activate > nodebb restart 

main.js:23 Uncaught TypeError: Cannot read property 'length' of null
    at HTMLAnchorElement.n (main.js:23)
    at HTMLAnchorElement.dispatch (jquery.js:5206)
    at HTMLAnchorElement.g.handle (jquery.js:5014)

**Comment by hariom282538** [comment]
@tailot 

> I forked this and solved this issue.

[https://github.com/hariom282538/nodebb-plugin-text2speech](https://github.com/hariom282538/nodebb-plugin-text2speech)

**Comment by tailot** [comment]
@hariom282538 thanks :cake: :cake: , i have marged!!
